### ISSUE TITLE
When YAML parsing fails

### ISSUE THREAD

**Issue by Genius3435** [vEnhance/von#13]
Sometimes (for example, if you include a `:` in one of the headers), Python fails to parse the YAML, and this causes the entire written solution to be deleted. An example:
![image](https://user-images.githubusercontent.com/62397740/218344573-c5ab0153-5d39-4ff6-9ae8-7e5dd0df08d0.png)

Ideally, the code should output an error similar to when there is another issue in the YAML, for example when `path` doesn't exist.

**Comment by vEnhance** [comment]
Closed by #15.
